# Generated by Django 3.2 on 2021-05-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0005_alter_pin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='id',
            field=models.CharField(default='8191a7ede88749d6913d55b1d33d1b9b', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
