# Generated by Django 3.2 on 2021-05-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0006_alter_pin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='id',
            field=models.CharField(default='b0f1a13d-611e-46b0-b66e-b025fb7d0cac', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
