# Generated by Django 3.2 on 2021-05-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0007_alter_pin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='id',
            field=models.CharField(default='6a44fc4f639e41b085f176344115a902', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
