# Generated by Django 3.2 on 2021-05-11 23:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0008_alter_pin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f6c430b-a94f-499b-8628-36fdfc13e71d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
