# Generated by Django 3.2 on 2021-05-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0013_quicksave'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicksave',
            name='is_save',
            field=models.BooleanField(default=False),
        ),
    ]
