# Generated by Django 3.2 on 2021-05-16 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pin', '0014_quicksave_is_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicksave',
            name='user',
        ),
        migrations.AddField(
            model_name='quicksave',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
