# Generated by Django 3.2 on 2021-05-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0015_auto_20210516_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicksave',
            name='is_save',
        ),
    ]
