# Generated by Django 3.2 on 2021-05-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0017_auto_20210516_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
