# Generated by Django 3.2 on 2021-05-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0018_auto_20210517_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='pin',
            field=models.ManyToManyField(related_name='pin', to='pin.Pin'),
        ),
    ]
